FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        openssh-server \
        python3 \
        python3-pip \
        rsync \
        git \
        sudo \
        # Adaugă Java JRE - NECESAR pentru agentul Jenkins
        openjdk-17-jre \
    && pip3 install ansible \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Crearea utilizatorului Jenkins și configurarea SSH
RUN useradd -m -d /home/jenkins -s /bin/bash jenkins && \
    echo "jenkins:jenkins" | chpasswd && \
    mkdir -p /home/jenkins/.ssh && \
    chown -R jenkins:jenkins /home/jenkins/.ssh

RUN mkdir /var/run/sshd
RUN echo 'root:root' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# Copiază cheile SSH (asumând că s-au generat corect)
COPY secrets/jenkins_agent_ssh_key.pub /home/jenkins/.ssh/authorized_keys
RUN chmod 600 /home/jenkins/.ssh/authorized_keys && \
    chown jenkins:jenkins /home/jenkins/.ssh/authorized_keys

COPY secrets/ansible_server_key /home/jenkins/.ssh/id_ed25519
RUN chmod 600 /home/jenkins/.ssh/id_ed25519 && \
    chown jenkins:jenkins /home/jenkins/.ssh/id_ed25519

# Comanda de start
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]